package es.mgamallo.ayudadigitalizacion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.ProxySelector;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import chrriis.dj.nativeswing.swtimpl.NativeComponent;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Manuel
 */
public class VentanaSetUp extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSetUp
     */
	
	Modelo modeloActual = new Modelo();
	
	
	Dimension dimPanel1 = new Dimension(1300,1150);
	Dimension dimPanel2 = new Dimension(400,1150);
	
	CargaListaPdfs pdfs;
	
	private int indexBorrar = -1;
	private PopupMenu menuPop = new PopupMenu();
	private MenuItem itemBorrar = new MenuItem("Borrar registro");
	
	public String proximoIndice = "";
	public int filaDondeEscribir;

	private boolean imagenExtraida = false;
	
	private JButton botonAnterior;

	private JButton botonRegistrar;

	private JLabel labelDocumento1;

	private JLabel labelDocumento2;

	private JLabel labelServicio;

	private JSeparator jSeparator1;

	private JLabel labelOrientacion;

	private JComboBox comboOrientacion;

	private JLabel labelFormato;

	private JComboBox comboFormato;
	
	private JLabel labelUrgencias;

	private JComboBox comboUrgencias;

	private JLabel labelIdentificaNHC;

	private JLabel labelIdentificaCIP;

	private JLabel labelIdentificaNSS;

	private JTextField campoIdentificaNHC;

	private JTextField campoIdentificaNSS;

	private JTextField campoIdentificaCIP;

	private JLabel labelDocYservicio;

	private JTextField campoDocYservicio;

	private JTextField campoDocumento1;

	private JTextField campoDocumento2;

	private JTextField campoServicio;
	
	private String rutasPdfs[];
	
	private int indiceArchivoSelecc = 0;
	
    public VentanaSetUp(String proximoIndice, int filaDondeEscribir) {
    	this.proximoIndice = proximoIndice;
    	this.filaDondeEscribir = filaDondeEscribir;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel0 = new javax.swing.JPanel();
        jSplitPane0 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Inicio.listaPdfs = new javax.swing.JList();
        jSplitPane1 = new javax.swing.JSplitPane();
        
        
        
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        
        panelSetupAyuda = new javax.swing.JPanel();
        panelSetupOCR = new javax.swing.JPanel();
        
        Inicio.webBrowser = new JWebBrowser();
       //  webBrowser.navigate("http://www.google.es");
       // webBrowser.navigate("F:/Desarrollo/git/AyudaDigitalizacion/AyudaDigitalizacion/ocr.pdf");
        Inicio.webBrowser.setVisible(false);
        
        Inicio.webBrowser.setBarsVisible(false);
        Inicio.webBrowser.setMenuBarVisible(false);
        Inicio.webBrowser.setJavascriptEnabled(true);
                
        //  Variables del panelOCR *********************************************
 
        
        botonAnterior = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        labelDocumento1 = new javax.swing.JLabel();
        labelDocumento2 = new javax.swing.JLabel();
        labelServicio = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelOrientacion = new javax.swing.JLabel();
        comboOrientacion = new javax.swing.JComboBox();
        labelFormato = new javax.swing.JLabel();
        comboFormato = new javax.swing.JComboBox();
        labelUrgencias = new javax.swing.JLabel();
        comboUrgencias = new javax.swing.JComboBox();
        labelIdentificaNHC = new javax.swing.JLabel();
        labelIdentificaCIP = new javax.swing.JLabel();
        labelIdentificaNSS = new javax.swing.JLabel();
        campoIdentificaNHC = new javax.swing.JTextField();
        campoIdentificaCIP = new javax.swing.JTextField();
        campoIdentificaNSS = new javax.swing.JTextField();
        
        labelDocYservicio = new javax.swing.JLabel();
        
        campoDocYservicio = new javax.swing.JTextField();
        campoDocumento1 = new javax.swing.JTextField();
        campoDocumento2 = new javax.swing.JTextField();
        campoServicio = new javax.swing.JTextField();
        
        setTitle("Hermes");
        
        labelDocYservicio.setText("Identifica Documento y Servicio");
        labelDocumento1.setText("Identifica Documento 1");

        labelDocumento2.setText("Identifica Documento 2");

        labelServicio.setText("Identifica Servicio");

        labelOrientacion.setText("Orientación");

        comboOrientacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vertical", "Horizontal" }));
        comboOrientacion.setSelectedIndex(0);
        
        labelFormato.setText("Formato papel");

        comboFormato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A4", "A5", "A3" }));
        comboFormato.setSelectedIndex(0);
        
        labelUrgencias.setText("¿Pdf de documentación o de urgencias?");
        
        comboUrgencias.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Documentación", "Urgencias","Ambas" }));
        comboUrgencias.setSelectedIndex(0);
        
        labelIdentificaNHC.setText("Identifica NHC");
        labelIdentificaCIP.setText("Identifica CIP");
        labelIdentificaNSS.setText("Identifica NSS");
        
        menuPop.add(itemBorrar);
        
        
        
        
        botonRegistrar.setText("Registrar");
        botonRegistrar.setBackground(Color.green);
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(false);
            }
        });
        
        botonAnterior.setText("Anterior");
        botonAnterior.setBackground(Color.yellow);
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });
        
        
        //*********************************************************************
        
        //*************** Etiqueta imagen
        
        
        
       // etiquetaImagen = new JLabel();
        
        /*
        ImageIcon image = new ImageIcon("ocr_1.jpg");
        
        int scale = 2;
        
        int width = image.getIconWidth();
        int height = image.getIconHeight();
                
        BufferedImage buffer = new BufferedImage((int)width/scale, (int)height/scale, BufferedImage.SCALE_SMOOTH);
        
        Graphics2D graphics = buffer.createGraphics();
       // graphics.scale(scale, scale);
        
        image.paintIcon(null, graphics, 0, 0);
        graphics.dispose();
        
        etiquetaImagen = new JLabel(new ImageIcon(buffer));
        
        //etiquetaImagen.setIcon(new ImageIcon("ocr_1.jpg"));
        
        */
        
        etiquetaImagen = new JLabel();
       
        scrollServicios = new javax.swing.JScrollPane();
        listaServicios = new javax.swing.JList();
  
        comboNombresNormalizadoPdf = new javax.swing.JComboBox();
        comboNombresNormalizadoOcr = new javax.swing.JComboBox();
        labelMetadatos = new javax.swing.JLabel();
        campoMetadato1 = new javax.swing.JTextField();
        campoMetadato2 = new javax.swing.JTextField();
        campoMetadato3 = new javax.swing.JTextField();
        campoMetadato4 = new javax.swing.JTextField();
        campoMetadato5 = new javax.swing.JTextField();
        labelObservaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTextoObservaciones = new javax.swing.JTextArea();
        labelApariencia = new javax.swing.JLabel();
        comboApariencia = new javax.swing.JComboBox();
        labelNombreNormalizado = new javax.swing.JLabel();
        labelColor = new javax.swing.JLabel();
        comboColor = new javax.swing.JComboBox();
        botonSiguiente = new javax.swing.JButton();
        panelImagenPdf = new javax.swing.JPanel();
        botonImagen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu3 = new JMenu();
        jMenu4 = new JMenu();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        // setPreferredSize(new java.awt.Dimension(1100, 900));

        // jPanel0.setPreferredSize(new java.awt.Dimension(1100, 850));

        jSplitPane0.setDividerSize(10);
        jSplitPane0.setOneTouchExpandable(true);


        Inicio.listaPdfs.add(menuPop);
        Inicio.listaPdfs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Inicio.listaPdfs.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent ev){
        		pulsarListaPdfs(ev);
        	}
        	
        	public void mouseReleased(MouseEvent ev){
        		if(ev.isPopupTrigger() && Inicio.editando){
        			indexBorrar = Inicio.listaPdfs.locationToIndex(ev.getPoint());
        			menuPop.show(Inicio.listaPdfs, ev.getPoint().x + 30, ev.getPoint().y);
         			
        		}
        	}
		});
        
        itemBorrar.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				int aceptar = JOptionPane.showConfirmDialog(null, "Seguro que quiere borrar el registro");
				if(aceptar == JOptionPane.OK_OPTION){
					// Borrar todos los campos
					System.out.println("Borrando... " + indexBorrar + "  " + Inicio.listaModeloJpgs.get(indexBorrar).toString());
					int num = Integer.valueOf(Inicio.listaModeloJpgs.get(indexBorrar).toString());
					borrarRegistro(num);
				}
			}
		});
        
        
        jScrollPane3.setViewportView(Inicio.listaPdfs);

        jSplitPane0.setLeftComponent(jScrollPane3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(dimPanel1.width,dimPanel1.height));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inicio.webBrowser)
            //.addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Inicio.webBrowser)
            .addGap(0, 827, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(dimPanel2.width,dimPanel2.height));

        listaServicios.setModel(Inicio.listaModelServicios);
        scrollServicios.setViewportView(listaServicios);

        panelSetupAyuda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Ayuda General", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        comboNombresNormalizadoPdf.setModel(Inicio.comboModelNombres);
        comboNombresNormalizadoPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNombresNormalizadoActionPerformed(evt);
            }
        });
        
        comboNombresNormalizadoOcr.setModel(Inicio.comboModelNombres);
        comboNombresNormalizadoOcr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNombresNormalizadoActionPerformed(evt);
            }
        });

        labelMetadatos.setText("Metadatos");

        labelObservaciones.setText("Observaciones");

        areaTextoObservaciones.setColumns(20);
        areaTextoObservaciones.setRows(5);
        jScrollPane2.setViewportView(areaTextoObservaciones);

        labelApariencia.setText("Apariencia");

        comboApariencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "Cuadrícula", "Cuadro", "Dibujo", "Eco", "Esquema", "Foto", "Gráfico"}));

        labelNombreNormalizado.setText("Nombre Normalizado");

        labelColor.setText("Color");

        comboColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "Amarillo", "Azul", "Marrón", "Naranja", "Rojo", "Rosa", "Varios","Verde", "Violeta"}));

        botonSiguiente.setText("Siguiente");
        botonSiguiente.setBackground(Color.yellow);
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        // etiquetaImagen.setText("Imagen");
        
        // panelImagenPdf.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panelImagenPdfLayout = new javax.swing.GroupLayout(panelImagenPdf);
        panelImagenPdf.setLayout(panelImagenPdfLayout);
        panelImagenPdfLayout.setHorizontalGroup(
            panelImagenPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelImagenPdfLayout.setVerticalGroup(
            panelImagenPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );

        botonImagen.setText("Añadir Imagen");
        botonImagen.setBackground(Color.pink);
        botonImagen.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				System.out.println("hola");
				
				capturaImagen(rutasPdfs[indiceArchivoSelecc],1);
			}
		});

        javax.swing.GroupLayout panelSetupAyudaLayout = new javax.swing.GroupLayout(panelSetupAyuda);
        panelSetupAyuda.setLayout(panelSetupAyudaLayout);
        panelSetupAyudaLayout.setHorizontalGroup(
            panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSetupAyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSetupAyudaLayout.createSequentialGroup()
                        .addComponent(botonImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSiguiente))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(campoMetadato5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMetadato4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMetadato3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMetadato2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMetadato1)
                    .addComponent(comboApariencia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboNombresNormalizadoPdf, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboColor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImagenPdf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSetupAyudaLayout.createSequentialGroup()
                        .addGroup(panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObservaciones)
                            .addComponent(labelApariencia)
                            .addComponent(labelNombreNormalizado)
                            .addComponent(labelColor)
                            .addComponent(labelMetadatos))
                        .addGap(0, 173, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        
        panelSetupAyudaLayout.setVerticalGroup(
            panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupAyudaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelNombreNormalizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboNombresNormalizadoPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelMetadatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelApariencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboApariencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelObservaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImagenPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonImagen))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(scrollServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSetupAyuda, 300, javax.swing.GroupLayout.DEFAULT_SIZE, 300))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollServicios)
            .addComponent(panelSetupAyuda, 1100, 1100, 1100)
        );

        jSplitPane1.setRightComponent(jPanel2);

        jSplitPane0.setRightComponent(jSplitPane1);
        
        jSplitPane0.setDividerLocation(150);

        javax.swing.GroupLayout jPanel0Layout = new javax.swing.GroupLayout(jPanel0);
        jPanel0.setLayout(jPanel0Layout);
        jPanel0Layout.setHorizontalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel0Layout.setVerticalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel0Layout.createSequentialGroup()
                .addComponent(jSplitPane0, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        
        
        ///////////////////////   Panel ocr
        
        panelSetupOCR.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro OCR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        
        javax.swing.GroupLayout panelSetupOCRLayout = new javax.swing.GroupLayout(panelSetupOCR);
        panelSetupOCR.setLayout(panelSetupOCRLayout);
        panelSetupOCRLayout.setHorizontalGroup(
            panelSetupOCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupOCRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSetupOCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSetupOCRLayout.createSequentialGroup()
                        .addGroup(panelSetupOCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDocYservicio)
                            .addComponent(labelDocumento1)
                            .addComponent(labelDocumento2)
                            .addComponent(labelServicio)
                            .addComponent(labelOrientacion)
                            .addComponent(labelFormato)
                            .addComponent(labelUrgencias))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSetupOCRLayout.createSequentialGroup())
                    	.addGroup(panelSetupOCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                        .addComponent(labelIdentificaNHC)
	                        .addComponent(labelIdentificaCIP)
	                        .addComponent(labelIdentificaNSS)
	                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSetupOCRLayout.createSequentialGroup()
                        .addGroup(panelSetupOCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRegistrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoIdentificaNHC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoIdentificaCIP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoIdentificaNSS, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFormato, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboOrientacion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboUrgencias, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoServicio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDocumento2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDocumento1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDocYservicio)
                            .addComponent(comboNombresNormalizadoOcr, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSetupOCRLayout.createSequentialGroup()
                                .addComponent(labelNombreNormalizado)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSetupOCRLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonAnterior)))
                        .addGap(23, 23, 23))))
        );
        panelSetupOCRLayout.setVerticalGroup(
            panelSetupOCRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupOCRLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelNombreNormalizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboNombresNormalizadoOcr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDocYservicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDocYservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(labelDocumento1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(labelDocumento2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOrientacion)
                .addGap(1, 1, 1)
                .addComponent(comboOrientacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelFormato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboFormato, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUrgencias)
                .addGap(1, 1, 1)
                .addComponent(comboUrgencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)                
                .addGap(18, 18, 18)
                .addComponent(labelIdentificaNHC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoIdentificaNHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
               .addComponent(labelIdentificaCIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)                
                .addGap(18, 18, 18)
                .addComponent(campoIdentificaCIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelIdentificaNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)                
                .addGap(18, 18, 18)                
                .addComponent(campoIdentificaNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				
				Inicio.editando = false;
				imagenExtraida = false;
				
				pdfs = new CargaListaPdfs();
				
				if(pdfs.nombrePdfs.length > 0){
					DefaultListModel listaModeloPdfs = new DefaultListModel();
					
					rutasPdfs = new String[pdfs.nombrePdfs.length];
					
					for(int i=0;i<pdfs.nombrePdfs.length;i++){
						listaModeloPdfs.addElement(pdfs.nombrePdfs[i]);
						rutasPdfs[i] = pdfs.rutaPdfs[i];
					}
					
					Inicio.listaPdfs.setModel(listaModeloPdfs);
					indiceArchivoSelecc = 0;
					Inicio.listaPdfs.setSelectedIndex(indiceArchivoSelecc);
					Inicio.webBrowser.navigate(rutasPdfs[indiceArchivoSelecc]);
					
					Inicio.webBrowser.setVisible(true);
				}

			}
		});
        
        
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");
        jMenu3.setText("Indexar");
        jMenu4.setText("Salir");

        jMenuItem2.setText("Editar");
        jMenu2.add(jMenuItem2);
        
        jMenuItem2.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				Inicio.editando = true;
				reseteaCampos();
				new VentanaDialogoRevisar();
			}
		});
                
        jMenuItem3.setText("Indexar tabla de ayuda");
        jMenu3.add(jMenuItem3);
        
        jMenuItem3.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				new AyudaIndex(false, true);
			}
		});
        
        jMenuItem4.setText("Salir indexando");
        jMenuItem4.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				new AyudaIndex(false, true);
				System.exit(0);
			}
		});
        
        jMenu4.add(jMenuItem4);
        jMenu4.add(jMenuItem5);
        
        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				System.exit(0);
			}
		});

        jMenuBar1.add(jMenu2);
        jMenuBar1.add(jMenu3);
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              //  .addGap(0, 850, Short.MAX_VALUE)
                )
        );
        
       setSize(1900,1180);
       setResizable(true);

       // pack();
    }// </editor-fold>                        

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    	
    	if(listaServicios.getSelectedIndices().length == 0){
    		JOptionPane.showMessageDialog(null, "Selecciona algún servicio, o todos los servicios");
    	}
    	else if(!imagenExtraida){
    		JOptionPane.showMessageDialog(null, "Extrae primero la imagen.");
    	}
    	else{
	    	modeloActual.identificador = proximoIndice;
	    	modeloActual.nombreNormalizado = comboNombresNormalizadoPdf.getSelectedItem().toString();
	    	
	    	ArrayList<String> servicios = new ArrayList<String>();
	    	
	    	for(int i=0;i<listaServicios.getSelectedIndices().length;i++){
	    		servicios.add(listaServicios.getSelectedValues()[i].toString());
	    	}
	    	
	    	modeloActual.pdf.servicios = servicios;
	    	
	    	modeloActual.pdf.metadatos[0] = campoMetadato1.getText();
	    	modeloActual.pdf.metadatos[1] = campoMetadato2.getText();   	
	    	modeloActual.pdf.metadatos[2] = campoMetadato3.getText();
	    	modeloActual.pdf.metadatos[3] = campoMetadato4.getText();
	    	modeloActual.pdf.metadatos[4] = campoMetadato5.getText();
	    	
	    	modeloActual.pdf.observaciones = areaTextoObservaciones.getText();
	    	modeloActual.pdf.fisica.apariencia = comboApariencia.getSelectedItem().toString();
	    	modeloActual.pdf.fisica.color = comboColor.getSelectedItem().toString();
	    	
	    	System.out.println(modeloActual.nombreNormalizado);
	    	for(int i=0;i<modeloActual.pdf.servicios.size();i++){
	    		System.out.println("   " + modeloActual.pdf.servicios.get(i));
	    	}
	    	
	    	for(int i=0;i<modeloActual.pdf.metadatos.length;i++){
	    		System.out.println(modeloActual.pdf.metadatos[i]);
	    	}
	    	
	    	System.out.println(modeloActual.pdf.observaciones);
	    	System.out.println(modeloActual.pdf.fisica.apariencia);
	    	System.out.println(modeloActual.pdf.fisica.color);
	
	     	
	    	jPanel2.removeAll();
	    	
	    	
	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	            	.addComponent(scrollServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(panelSetupOCR, 300, javax.swing.GroupLayout.DEFAULT_SIZE, 300))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(scrollServicios)
	            .addComponent(panelSetupOCR, 1150, 1150, 1150)
	        );
    	}
    	
      //  comboNombresNormalizado.
 
    	
    }                                              

    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed
        // TODO add your handling code here:
    	
    	jPanel2.removeAll();
    	
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(scrollServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSetupAyuda, 300, javax.swing.GroupLayout.DEFAULT_SIZE, 300))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollServicios)
            .addComponent(panelSetupAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    	
    	
    }//GEN-LAST:event_botonAnteriorActionPerformed
    
    private void pulsarListaPdfs(MouseEvent ev){
    	
    	imagenExtraida = false;
    	
    	if(Inicio.editando){
           	if(ev.getButton() == 1){
        		System.out.println("Boton izquierdo");

            		//indiceArchivoSelecc = Inicio.listaPdfs.getSelectedIndex();
            		
            		int indice = Integer.valueOf(Inicio.listaPdfs.getSelectedValue().toString());
            		
        			String proximoIndice = "";
    	        	if(indice > 999 && indice < 10000 ){
    	        		proximoIndice += "0";
    	        	}
    	        	else if(indice > 99 && indice < 1000 ){
    	        		proximoIndice += "00";
    	        	}
    	        	else if(indice > 9 && indice < 100 ){
    	        		proximoIndice += "000";
    	        	}
    	        	else if(indice < 10 ){
    	        		proximoIndice += "0000";
    	        	}
        			
        			
                	proximoIndice += indice;
        			String ruta = Inicio.rutaHermes + "\\Index_" + proximoIndice + ".jpg";
            		
            		
            		
            		reseteaCampos();
            		
            		String html = "<html> <body> <img src='" + ruta 
            				+ "' width='750px'> </body> </html>";

            		Inicio.webBrowser.setHTMLContent(html);
            		imagenExtraida = true;

            		actualizaCampos(indice);
            		
            		
        		    		
        	}else if(ev.getButton() == 2){
        		System.out.println("Boton central");
        	}
        	else{
        		System.out.println("Boton derecho");
        	}
    	}

    	else{
           	if(ev.getButton() == 1){
        		System.out.println("Boton izquierdo");
        		int i= JOptionPane.showConfirmDialog(null, "Se van a resetear los campos. ¿Desea continuar?");
        		if(i == JOptionPane.OK_OPTION){
            		indiceArchivoSelecc = Inicio.listaPdfs.getSelectedIndex();
            		
            		reseteaCampos();
            		
            		System.out.println(rutasPdfs[indiceArchivoSelecc]);
            		Inicio.webBrowser.navigate(rutasPdfs[indiceArchivoSelecc]);
            		imagenExtraida = false;
        		}
        		else{
        			Inicio.listaPdfs.setSelectedIndex(indiceArchivoSelecc);
        		}
        		
        		    		
        	}else if(ev.getButton() == 2){
        		System.out.println("Boton central");
        	}
        	else{
        		System.out.println("Boton derecho");
        	}
    	}

    }
    
    private void botonRegistrarActionPerformed(boolean borrar) {//GEN-FIRST:event_botonAnteriorActionPerformed
        // TODO add your handling code here:
    	
    	modeloActual.nombreNormalizado = comboNombresNormalizadoOcr.getSelectedItem().toString();
    	
    	ArrayList<String> servicios = new ArrayList<String>();
    	
    	if(!borrar){
        	for(int i=0;i<listaServicios.getSelectedIndices().length;i++){
        		servicios.add(listaServicios.getSelectedValues()[i].toString());
        	}
        	    	
        	modeloActual.pdf.servicios = servicios;
    	}
    	else{
    		servicios.add("");
    		modeloActual.pdf.servicios = servicios;
    	}

    	
    	modeloActual.ocr.metadatos[0] = campoDocYservicio.getText();
    	modeloActual.ocr.metadatos[1] = campoDocumento1.getText();   	
    	modeloActual.ocr.metadatos[2] = campoDocumento2.getText();
    	modeloActual.ocr.metadatos[3] = campoServicio.getText();
    	
    	modeloActual.ocr.identificaNhc = campoIdentificaNHC.getText();
    	modeloActual.ocr.identificaCIP = campoIdentificaCIP.getText();
    	modeloActual.ocr.identificaNSS = campoIdentificaNSS.getText();
    	
    	modeloActual.pdf.observaciones = areaTextoObservaciones.getText();
    	
    	if(!borrar){
        	modeloActual.pdf.fisica.orientacion = comboOrientacion.getSelectedItem().toString(); 
        	modeloActual.pdf.fisica.formato = comboFormato.getSelectedItem().toString();
        	modeloActual.ocr.urgOdocumentacion = comboUrgencias.getSelectedItem().toString();
    	}
    	else{
          	modeloActual.pdf.fisica.orientacion = ""; 
        	modeloActual.pdf.fisica.formato = "";
        	modeloActual.ocr.urgOdocumentacion = "";
        	
        	modeloActual.pdf.fisica.color = "";
        	modeloActual.pdf.fisica.apariencia = "";
    	}

    	
/*
    	
    	for(int i=0;i<modeloActual.pdf.servicios.size();i++){
    		System.out.println("   " + modeloActual.pdf.servicios.get(i));
    	}
    	
    	for(int i=0;i<modeloActual.ocr.metadatos.length;i++){
    		System.out.println(modeloActual.pdf.metadatos[i]);
    	}
    	
    	System.out.println(modeloActual.ocr.identificaNhc);
    	System.out.println(modeloActual.pdf.fisica.orientacion);
    	System.out.println(modeloActual.pdf.fisica.formato);
*/
     	
    	jPanel2.removeAll();
    	
    	if(Inicio.editando){
    		int indice = Integer.valueOf(Inicio.listaPdfs.getSelectedValue().toString());
    		System.out.println("Fila donde escribir... " + indice);
			
			String proximoIndice = "";
        	if(indice > 999 && indice < 10000 ){
        		proximoIndice += "0";
        	}
        	else if(indice > 99 && indice < 1000 ){
        		proximoIndice += "00";
        	}
        	else if(indice > 9 && indice < 100 ){
        		proximoIndice += "000";
        	}
        	else if(indice < 10 ){
        		proximoIndice += "0000";
        	}
			
        	proximoIndice += indice;
    		
    		
        	modeloActual.identificador = "Index_" + proximoIndice;
    		
        	EscribeExcel escribe = new EscribeExcel();
        	boolean exito = escribe.escribir(Inicio.HERMES_XLS, modeloActual, indice, true);
        	
        	if(exito){
        		JOptionPane.showMessageDialog(null, "Modificación realizada con éxito.");
        		new AyudaIndex(true, true);
        	}
        	else{
        		JOptionPane.showMessageDialog(null, "Modificación no realizada.");
        	}
        	
        	
    	}
    	else{
        	System.out.println("Fila donde escribir... " + filaDondeEscribir);
        	
        	EscribeExcel escribe = new EscribeExcel();
        	boolean exito = escribe.escribir(Inicio.HERMES_XLS, modeloActual, filaDondeEscribir,false);
        	
        	if(exito){
            	reseteaCampos();
            	JOptionPane.showMessageDialog(null, "Modelo registrado");
            	
            	Inicio.leerExcel.leerAyuda(Inicio.HERMES_XLS);
            	proximoIndice = Inicio.leerExcel.proximoIndice;
            	filaDondeEscribir = Inicio.leerExcel.ultimaFila;
            	
    	    	System.out.println("PróximoIndice... " + proximoIndice);
    	    	
            	if(!mueveOeliminaImagen(true)){
            		JOptionPane.showMessageDialog(null, "No se pudo mover la imagen temporal");
            	}
            	imagenExtraida = false;
        	}

      //************************************************************************  	    	
    		
        	if(rutasPdfs.length > ++indiceArchivoSelecc){
        		Inicio.listaPdfs.setSelectedIndex(indiceArchivoSelecc);
            	Inicio.webBrowser.navigate(rutasPdfs[indiceArchivoSelecc]);
        	}
    	}

    	
    	
    	/*
    	DefaultListModel listaModeloPdfs = new DefaultListModel();
		
		ArrayList arrayAux = new ArrayList();
		
		for(int i=0;i<pdfs.nombrePdfs.length;i++){
			if(i != indiceArchivoSelecc){
				arrayAux.add(pdfs.nombrePdfs[i]);
			}
		}
		
		Object arrayAux2[] = arrayAux.toArray();
		
		String arrayAux3[] = new String[arrayAux2.length];
		
		pdfs.nombrePdfs = arrayAux3;
		
		rutasPdfs = new String[pdfs.nombrePdfs.length];
		
		for(int i=0;i<pdfs.nombrePdfs.length;i++){
			listaModeloPdfs.addElement(pdfs.nombrePdfs[i]);
			rutasPdfs[i] = pdfs.rutaPdfs[i];
		}
		
		listaPdfs.setModel(listaModeloPdfs);
		*/
    	
		//**************************************************************************************
    	
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(scrollServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSetupAyuda, 300, javax.swing.GroupLayout.DEFAULT_SIZE, 300))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollServicios)
            .addComponent(panelSetupAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    	
        
    	
    }//GEN-LAST:event_botonAnteriorActionPerformed
    
    
    private void reseteaCampos(){
    	
    	comboOrientacion.setSelectedIndex(0);
    	comboFormato.setSelectedIndex(0);
    	comboUrgencias.setSelectedIndex(0);
    	comboApariencia.setSelectedIndex(0);
    	comboColor.setSelectedIndex(0);
    	comboNombresNormalizadoPdf.setSelectedIndex(0);
    	comboNombresNormalizadoOcr.setSelectedIndex(0);
    	areaTextoObservaciones.setText("");
    	
    	campoIdentificaNHC.setText("");
    	campoIdentificaCIP.setText("");
    	campoIdentificaNSS.setText("");
    	
    	campoDocYservicio.setText("");
    	campoDocumento1.setText("");
    	campoDocumento2.setText("");
    	campoServicio.setText("");
    	
    	campoMetadato1.setText("");
    	campoMetadato2.setText("");
    	campoMetadato3.setText("");
    	campoMetadato4.setText("");
    	campoMetadato5.setText("");
    	
    	listaServicios.clearSelection();
    	    	
    	etiquetaImagen.setIcon(null);
    	
    }
    
    private boolean mueveOeliminaImagen(boolean mover){
    	
    	if(mover){
        	File imagenTemporal = new File(Inicio.rutaImagenesTemp + modeloActual.identificador + ".jpg");
        	File imagenDefinitiva = new File(Inicio.rutaImagenes + modeloActual.identificador + ".jpg");
        	
        	boolean exito = imagenTemporal.renameTo(imagenDefinitiva);
        	return exito;
    	}
    	else{
           	File imagenTemporal = new File(Inicio.rutaImagenesTemp + modeloActual.identificador + ".jpg");
           	return imagenTemporal.delete();
    	}
    }
    
    private void comboNombresNormalizadoActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    /*
     * Métodos propios
     */
    
    public void setPdf(){
    	Inicio.webBrowser.navigate("d:\\Desarrollo\\git\\AyudaDigitalizacion\\AyudaDigitalizacion\\ocr.pdf");
    }
    
    private void capturaImagen(String ruta, int indice){
    	
    	if(!Inicio.editando){
        	PdfToImage image = new PdfToImage(ruta,proximoIndice);
        	
            ImageIcon fot = new ImageIcon(Inicio.rutaImagenesTemp + proximoIndice + ".jpg");
            Icon icono = new ImageIcon(fot.getImage().getScaledInstance(150, 200, Image.SCALE_SMOOTH));
            
            etiquetaImagen.setIcon(icono);
            imagenExtraida = true;
            this.repaint();
    	}

   	
    }
    
    public void borrarRegistro(int indice){
    	
    	reseteaCampos();
    	
    	comboOrientacion.removeAllItems();
    	comboOrientacion.addItem("");
    	comboFormato.removeAllItems();
    	comboFormato.addItem("");
    	comboUrgencias.removeAllItems();
    	comboUrgencias.addItem("");
    	comboApariencia.removeAllItems();
    	comboApariencia.addItem("");
    	comboColor.removeAllItems();
    	comboColor.addItem("");
    	
    	listaServicios.removeAll();
    	
    	botonRegistrarActionPerformed(true);
    	
    }
    
    public void actualizaCampos(int indice){
    	String ayuda[][] = Inicio.leerExcel.getTablaHermesAyuda();
    	String ocr[][] = Inicio.leerExcel.getTablaHermesOCR();
    	
    	comboNombresNormalizadoPdf.setSelectedItem(ayuda[indice-1][1]);
    	
    	campoMetadato1.setText(ayuda[indice-1][2].toString());
    	campoMetadato2.setText(ayuda[indice-1][3].toString());
    	campoMetadato3.setText(ayuda[indice-1][4].toString());
    	campoMetadato4.setText(ayuda[indice-1][5].toString());
    	campoMetadato5.setText(ayuda[indice-1][6].toString());
    	
        comboApariencia.setSelectedItem(ayuda[indice-1][7].toString()); 
        comboColor.setSelectedItem(ayuda[indice-1][8].toString()); 
        
        String serv[] = ayuda[indice-1][9].split(",");
        
        listaServicios.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
        int indices[] = new int[serv.length];
        for(int i=0,z=0;i<Inicio.listaModelServicios.size() && z < serv.length;i++){
        	System.out.println(Inicio.listaModelServicios.getElementAt(i));
        	
        	if(Inicio.listaModelServicios.getElementAt(i).toString().equals(serv[z])){
        		indices[z] = i;
        		z++;
        	}
        }
 
        listaServicios.setSelectedIndices(indices);
        
        areaTextoObservaciones.setText(ayuda[indice-1][10].toString());
        
        campoDocYservicio.setText(ocr[indice-1][9].toString());
        campoDocumento1.setText(ocr[indice-1][7].toString());
        campoDocumento2.setText(ocr[indice-1][8].toString());
        campoServicio.setText(ocr[indice-1][6].toString());
        
        comboOrientacion.setSelectedItem(ocr[indice-1][3].toString());
        comboFormato.setSelectedItem(ocr[indice-1][4].toString());
        comboUrgencias.setSelectedItem(ocr[indice-1][5].toString());
        
        
    	campoIdentificaNHC.setText(ocr[indice-1][10].toString());

    	campoIdentificaNSS.setText(ocr[indice-1][11].toString());

    	campoIdentificaCIP.setText(ocr[indice-1][12].toString());

        
      //  listaServicios.setSelected;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSetUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new VentanaSetUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea areaTextoObservaciones;
    private javax.swing.JButton botonImagen;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField campoMetadato1;
    private javax.swing.JTextField campoMetadato2;
    private javax.swing.JTextField campoMetadato3;
    private javax.swing.JTextField campoMetadato4;
    private javax.swing.JTextField campoMetadato5;
    private javax.swing.JComboBox comboApariencia;
    private javax.swing.JComboBox comboColor;
    private javax.swing.JComboBox comboNombresNormalizadoPdf;
    private javax.swing.JComboBox comboNombresNormalizadoOcr;    
    private javax.swing.JList listaServicios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel0;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane0;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelApariencia;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelMetadatos;
    private javax.swing.JLabel labelNombreNormalizado;
    private javax.swing.JLabel labelObservaciones;
    private javax.swing.JPanel panelImagenPdf;
    private javax.swing.JPanel panelSetupAyuda;
    private javax.swing.JPanel panelSetupOCR;
    private javax.swing.JScrollPane scrollServicios;

    private JLabel etiquetaImagen;
    // End of variables declaration                   
}
