/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package es.mgamallo.ayudadigitalizacion;

import java.awt.Color;

import javax.swing.GroupLayout;

import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;

/**
 *
 * @author Manuel
 */
public class VentanaSetUpAyuda extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSetUp
     */
    public VentanaSetUpAyuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        
        webBrowser = new JWebBrowser();
        webBrowser.navigate("http://www.google.es");
        webBrowser.setBarsVisible(false);
        webBrowser.setMenuBarVisible(false);
                
        scrollServicios = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        panelSetupAyuda = new javax.swing.JPanel();
        comboNombresNormalizado = new javax.swing.JComboBox();
        labelMetadatos = new javax.swing.JLabel();
        campoMetadato1 = new javax.swing.JTextField();
        campoMetadato2 = new javax.swing.JTextField();
        campoMetadato3 = new javax.swing.JTextField();
        campoMetadato4 = new javax.swing.JTextField();
        campoMetadato5 = new javax.swing.JTextField();
        labelObservaciones = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTextoObservaciones = new javax.swing.JTextArea();
        labelApariencia = new javax.swing.JLabel();
        comboApariencia = new javax.swing.JComboBox();
        labelNombreNormalizado = new javax.swing.JLabel();
        labelColor = new javax.swing.JLabel();
        comboColor = new javax.swing.JComboBox();
        botonSiguiente = new javax.swing.JButton();
        panelImagenPdf = new javax.swing.JPanel();
        botonImagen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1900, 1150));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1900, 1150));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webBrowser)
           // .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(webBrowser)
           // .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrollServicios.setViewportView(jList1);

        panelSetupAyuda.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Ayuda General", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        comboNombresNormalizado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNombresNormalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNombresNormalizadoActionPerformed(evt);
            }
        });

        labelMetadatos.setText("Metadatos");

        labelObservaciones.setText("Observaciones");

        areaTextoObservaciones.setColumns(20);
        areaTextoObservaciones.setRows(5);
        jScrollPane2.setViewportView(areaTextoObservaciones);

        labelApariencia.setText("Apariencia");

        comboApariencia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "Cuadrícula", "Cuadro", "Dibujo", "Eco", "Esquema", "Foto", "Gráfica", " ", " ", " " }));

        labelNombreNormalizado.setText("Nombre Normalizado");

        labelColor.setText("Color");

        comboColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ninguno", "Amarillo", "Azul", "Marrón", "Naranja", "Rojo", "Rosa", "Verde", "Violeta", " " }));

        botonSiguiente.setText("Siguiente");
        botonSiguiente.setBackground(Color.yellow);
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        panelImagenPdf.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout panelImagenPdfLayout = new javax.swing.GroupLayout(panelImagenPdf);
        panelImagenPdf.setLayout(panelImagenPdfLayout);
        panelImagenPdfLayout.setHorizontalGroup(
            panelImagenPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelImagenPdfLayout.setVerticalGroup(
            panelImagenPdfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 183, Short.MAX_VALUE)
        );

        botonImagen.setText("Añadir Imagen");

        javax.swing.GroupLayout panelSetupAyudaLayout = new javax.swing.GroupLayout(panelSetupAyuda);
        panelSetupAyuda.setLayout(panelSetupAyudaLayout);
        panelSetupAyudaLayout.setHorizontalGroup(
            panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSetupAyudaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSetupAyudaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonSiguiente))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(campoMetadato5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMetadato4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMetadato3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMetadato2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoMetadato1)
                    .addComponent(comboApariencia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboNombresNormalizado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboColor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImagenPdf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSetupAyudaLayout.createSequentialGroup()
                        .addGroup(panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelObservaciones)
                            .addComponent(labelApariencia)
                            .addComponent(labelNombreNormalizado)
                            .addComponent(labelColor)
                            .addComponent(labelMetadatos)
                            .addComponent(botonImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        panelSetupAyudaLayout.setVerticalGroup(
            panelSetupAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupAyudaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelNombreNormalizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboNombresNormalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelMetadatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMetadato5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelApariencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboApariencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelObservaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelImagenPdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(scrollServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSetupAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollServicios)
            .addComponent(panelSetupAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, 1900, 1900, 1900)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, 1900, 1900, 1900)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, 1100, 1100, 1100)
            .addComponent(jPanel2, 1100, 1100, 1100)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void comboNombresNormalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNombresNormalizadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNombresNormalizadoActionPerformed

    
    public void setPdf(){
    	webBrowser.navigate("K:\\Desarrollo\\git\\AyudaDigitalizacion\\AyudaDigitalizacion\\arreglar.pdf");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSetUpAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSetUpAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSetUpAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSetUpAyuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSetUpAyuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTextoObservaciones;
    private javax.swing.JButton botonImagen;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField campoMetadato1;
    private javax.swing.JTextField campoMetadato2;
    private javax.swing.JTextField campoMetadato3;
    private javax.swing.JTextField campoMetadato4;
    private javax.swing.JTextField campoMetadato5;
    private javax.swing.JComboBox comboApariencia;
    private javax.swing.JComboBox comboColor;
    private javax.swing.JComboBox comboNombresNormalizado;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelApariencia;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelMetadatos;
    private javax.swing.JLabel labelNombreNormalizado;
    private javax.swing.JLabel labelObservaciones;
    private javax.swing.JPanel panelImagenPdf;
    private javax.swing.JPanel panelSetupAyuda;
    private javax.swing.JScrollPane scrollServicios;
    public JWebBrowser webBrowser;
    // End of variables declaration//GEN-END:variables
}
